on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  schedule:
    - cron: "0 10 * * 1"

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "${{ github.repository }}"
  ARGO_VERSION: "2.5.4"
  AVP_VERSION: "1.13.1"

jobs:
  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,event=push,enable=true,prefix=branch-{{ branch }}-git-,format=short
            type=raw,event=push,enable={{ is_default_branch }},value=argocd${{ env.ARGO_VERSION }}-avp${{ env.AVP_VERSION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ARGO_VERSION=${{ env.ARGO_VERSION }}
            AVP_VERSION=${{ env.AVP_VERSION }}
